# Generated by Django 3.2.4 on 2021-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_droid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='gpio_bcm',
            field=models.PositiveSmallIntegerField(help_text='GPIO Port Number', unique=True),
        ),
    ]
