# Generated by Django 3.2.4 on 2021-06-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_droid', '0004_pentairpump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentairpump',
            name='pump_address',
            field=models.PositiveSmallIntegerField(choices=[(15, 'BROADCAST'), (16, 'SUNTOUCH'), (32, 'EASYTOUCH'), (33, 'REMOTE_CONTROLLER'), (34, 'REMOTE_WIRELESS_CONTROLLER'), (72, 'QUICKTOUCH'), (96, 'INTELLIFLO_PUMP_1'), (97, 'INTELLIFLO_PUMP_2'), (98, 'INTELLIFLO_PUMP_3'), (99, 'INTELLIFLO_PUMP_4'), (100, 'INTELLIFLO_PUMP_5'), (101, 'INTELLIFLO_PUMP_6'), (102, 'INTELLIFLO_PUMP_7'), (103, 'INTELLIFLO_PUMP_8'), (104, 'INTELLIFLO_PUMP_9'), (105, 'INTELLIFLO_PUMP_10'), (106, 'INTELLIFLO_PUMP_11'), (107, 'INTELLIFLO_PUMP_12'), (108, 'INTELLIFLO_PUMP_13'), (109, 'INTELLIFLO_PUMP_14'), (110, 'INTELLIFLO_PUMP_15'), (111, 'INTELLIFLO_PUMP_16')]),
        ),
    ]
